version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:latest
    container_name: medinaz_wordpress
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - medinaz

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: medinaz-webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - medinaz

  #MySQL Service
  db:
    image: latest
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - medinaz

#Docker Networks
networks:
  medinaz:
    driver: bridge
